# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b2a604da-91c9-470e-840c-481ec4a79d81'
  imageRepository: 'abbu'
  containerRegistry: 'jhansirepo.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
    steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
        - task: Docker@2
          inputs:
            containerRegistry: 'jhansirepo'
            repository: 'achu'
            command: 'build'
            Dockerfile: '**/Dockerfile'
        - task: Docker@2
          inputs:
            containerRegistry: 'jhansirepo'
            repository: 'achu'
            command: 'push'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - task: CopyFiles@2
          inputs:
            Contents: 'jhansi.yml'
            TargetFolder: '$(build.artifactstagingdirectory)'